.PHONY: dist
dist:
	mkdir -p ../elixir/assets/static
	rm -f ../elixir/assets/static/favicon.ico
	rm -f ../elixir/assets/static/robots.txt

	cp favicon.ico ../elixir/assets/static/
	cp robots.txt ../elixir/assets/static/
