.PHONY: dist

dist:
	rm -rf ../elixir/assets/static/material-icons
	mkdir -p ../elixir/assets/static/material-icons

	cp MaterialIcons-Regular.eot   ../elixir/assets/static/material-icons
	cp MaterialIcons-Regular.ijmap ../elixir/assets/static/material-icons
	cp MaterialIcons-Regular.svg   ../elixir/assets/static/material-icons
	cp MaterialIcons-Regular.ttf   ../elixir/assets/static/material-icons
	cp MaterialIcons-Regular.woff  ../elixir/assets/static/material-icons
	cp MaterialIcons-Regular.woff2 ../elixir/assets/static/material-icons

	cp material-icons.css ../elixir/assets/static/material-icons
