.PHONY: dist

dist:
	rm -rf ../elixir/assets/static/markdown
	mkdir -p ../elixir/assets/static/markdown
	cp dist/easymde.min.css ../elixir/assets/static/markdown/markdown.css
	cp dist/easymde.min.js ../elixir/assets/static/markdown/markdown.js
	cp dist/marked.min.js ../elixir/assets/static/markdown/marked.js
